---
- hosts: all
  vars:
    prefix: '*'
    list: 
      - "a"
      - "b"
      - "c"
      - "d"
    list2: ['Apple','Banana','Cat', 'Dog']
    my_joined_list: "{{ list | join(prefix+',') }}"
  tasks:
    - name: Try Basic Template
      template:
        src: basic_template.j2
        dest: /tmp/try_basic_template.txt

    - name: Try Multiple Template
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - {src: 'basic_template.j2', dest: '/tmp/template1.out'}
        - {src: 'basic_template.j2', dest: '/tmp/template2.out'}
        - {src: 'basic_template.j2', dest: '/tmp/template3.out'}
     
    - name: Register Variable
      shell: uptime
      register: myuptime
      ignore_errors: True
    
    - name: Echo registered variables
      shell: echo {{myuptime}}

    - name: Try Encrypted File
      copy:
        src:  'myfile.txt'
        dest: '/tmp/try_encrypted_file.txt'

    - name: Try Variable From Group Vars
      copy:
        dest: "/tmp/try_variable_from_group_vars.txt"
        content: "{{ntp_server}}"

  roles:
    - mywebserver

- hosts: masters
  tasks:
    - name: Try Copy Files
      copy:
        src: file.lock 
        dest: /tmp/master.lock
        owner: root
        group: root
        mode: u+rw,g-wx,o-rwx 
